```{r}
library(dplyr)
library(stringr)
library(plotly)

source('functions.R')
source('body.R')
```

```{r}
f <- 'data/SEP22/master.xlsx'
readxl::excel_sheets(f)

df <- readxl::read_xlsx(f, 'master') %>% rename_with(.fn=make.names)
media_cols <- readxl::read_xlsx(f, "media_cols")[['0']] %>% make.names()
demo_cols <- readxl::read_xlsx(f, "demo_cols")[['0']] %>% make.names()
media_units <- readxl::read_xlsx(f, "media_units")
adstocks_init <- readxl::read_xlsx(f, "adstocks")

media_names_df <- read.csv('data/SEP22/media_names.csv')
```

```{r}
df$Week_num <- factor(df$Week)

#temp sol before remaking dataset

#get rid of NA coefs
media_units[media_units$varname == 'OTT_Roku_ProspectiveQLE_GM_Weber', 'selected'] = 'OTT_Roku_ProspectiveQLE_GM_Weber_Impressions'
#df <- df[,!(colnames(df) %in% c('acs_Uninsured.under.26_sum'))]
#demo_cols <- demo_cols[!(demo_cols %in% c('acs_Uninsured.under.26_sum'))]
```

```{r}
media_vars <- media_units$selected
names(media_vars) <- media_units$varname
```

```{r}
model_dir <- 'models/SEP22'
```

Percent model

model_args <- list(model='others', model_file = 'multicol.json', add_cols='Week_num', log=FALSE, scale='acs_Uninsured.under.65_sum')
#'acs_Uninsured.under.65_sum' #'uninsured_under65_uninsured_sum'

Log model
```{r}
model_args <- list(model='others', model_file = 'model1.json', add_cols='Week_num', log=TRUE, scale=1)
model_args <- c(model_params[[model_args$model]], model_args)

model1 <- modelClass$new(
  data=lst(df, media_vars, demo_cols, adstocks_init),
  model_args
)
model1$runOLS()

reg_sum <- summary(model1$reg)
#reg_sum
```

```{r}
neg <- Filter(function(x) x < 0, reg_sum$coefficients[,"Estimate"])
neg <- neg[names(neg) %in% model1$predictors_media]

#insig
insig <- Filter(function(x) x > .05, reg_sum$coefficients[,"Pr(>|t|)"])
insig <- insig[names(insig) %in% model1$predictors_media]

neg
insig

spends_sum <- read.csv('data/SEP22/spends.csv', row.names=1)
spends_sum$combined <- setNames(model1$combine_map, to_base_names(names(model1$combine_map)))[row.names(spends_sum)]
spends_sum$neg <- row.names(spends_sum) %in% to_base_names(names(neg))

high_spends <- spends_sum[spends_sum$neg,] %>% arrange(desc(spends)) %>% slice(1:3) %>% row.names()

sel_vars <- grep("^OnlineVideo_YouTube", model1$predictors_media, value=TRUE)

#can exclude easily with
#dput(names(neg))
```


```{r}
#params_search(c('Radio_Local_GM_Weber_GRPs'), model1)
params_search_dimret_adstock(c('TV_GM_GRPs'), model1)
#params_search_2d("TV_GM_GRPs", 
                 #"Radio_Local_GM_Weber_GRPs", model1)

#toJSON(model1$combine_dict, pretty=TRUE, auto_unbox=TRUE)
```

```{r}
library(reticulate)

use_condaenv("r-reticulate")
```

```{r}
var <- 'TV_GM'

system.time(max_results <- max_tstat(var, model1, iters=500L)) 

max_results$params
```

```{r}
#can show in Rstudio new window to view full size

plot_ly(
  z = model1$df_transformed[model1$predictors_media] %>% cor(),
  x = model1$predictors_media,
  y = model1$predictors_media,
  type = "heatmap", height=1800, width=1800
)
```

```{r}
#useful for dimret to see if there's remaining signal in residuals
plot(model1$df_transformed$TV_GM_GRPs, model1$reg$residuals)
plot(model1$df_transformed$OnlineVideo_YouTube_ProspectiveQLE_GM_Prospecting_Weber_Clicks, model1$reg$residuals)

#even vars that have not as high spend have this pattern
plot(model1$df_transformed$OnlineVideo_YouTube_QLE_Moving_GM_Prospecting_Weber_Clicks, model1$reg$residuals)

#plot(model1$df_transformed$Social_FB_ProspectiveQLE_GM_Prospecting_Weber_Clicks, model1$reg$residuals)

#check residuals follow normality
hist(model1$reg$residuals)
```

```{r}
 no_breakout <- c('TV_GM', 'Search_GM')

model1$create_results(no_breakout=no_breakout)

model1$effects_sum
```

```{r}
model1$preds %>% group_by(Week) %>% summarise(y=sum(y), y_fitted=sum(y_fitted)) %>% ggplot(aes(x=Week, group=1)) +
  geom_line(aes(y=y), color='red') + geom_line(aes(y=y_fitted), color='green')
```

